dist: trusty
sudo: required
language: c
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq linux-headers-`uname -r` libpcap0.8-dev libpcap0.8 
script: make clean && make all
deploy:
  provider: releases
  api_key:
    secure: blNmqFJxTZeErtjHrewbY6ET4at11bqNBMjtbzA741ZkB41ZmUVi851H4i35iFpyNVKiGbL925xwSST6CTJkELymqPc1GOiP7npCVPvzh6ET8cwY5mIPrN4GsSeHDTf1YiksqRwITtUZJxZveo3rFQRCid8HnIb/rwA7cADM3pSsacvMQGuNhZu4e4pVJogadb7G6a5Sa6sgZ8ZWgKm7CNxZQqESEb2NV+pCLD7mShkENF+L1ENB4fMVWL0mAhQrZt2d6hBqpwtr/1pCrFO9sSnSQXbI0JhWNaZri7pidF07/Gw7pOIifAlR3k9UYtOhWOTYVMcbZnByfCGfmLVbsstLQbot9gFK1b+gVBHD2JUncT4QW/QwgVW+xdDi2dV8/8F6+ym+7xys5JEeJ2Cg6/lI2phSOc4N1FAFaps7U1r2mhCFnsOnYm6RS4q9Q6SvSWZJdysGGlmFmVlcxLqumuacVu08+IaoZZfce3JUEnllrf/pMXvTSia11GJTYE87BqSV6tfJr0PeX4H/jUgHlH/7ne8P7RCW6V64pwMitzaqzN/EcMN3IUgbkPcwVnWHFhkRSuanqydCy99wtEn79eCCR3dBd/7EvwFZ2WApJl0Bf0YWka8+lQroqJ1c8uJo6io1tw5BBdJkeStNDwkZG8DuMgcp9oGxP21cAXTfZjE=
  file:
    - rx
    - tx
    - traffic_gen
  skip_cleanup: true
  on:
    repo: dmitry-kutergin/wifi_broadcast
